import type { AcquisitionSnapshot } from "@/lib/acquisition";

export const demoAcquisitionSnapshot: AcquisitionSnapshot = {
  mode: "demo",
  generatedAt: "2026-07-25T14:42:00.000Z",
  windowDays: 7,
  property: {
    id: "demo-web-property",
    name: "Car Dealer Tracker",
    domain: "cardealertracker.app",
    tokenVersion: 1,
    retentionDays: 90,
    createdAt: "2026-06-01T10:00:00.000Z",
  },
  totals: {
    visitors: 1248,
    sessions: 1391,
    pageviews: 3284,
    engaged: 712,
    converted: 84,
    online: 11,
    averageSessionSeconds: 93,
  },
  series: [
    { date: "2026-07-19", visitors: 126, engaged: 68, converted: 7 },
    { date: "2026-07-20", visitors: 154, engaged: 84, converted: 9 },
    { date: "2026-07-21", visitors: 139, engaged: 76, converted: 8 },
    { date: "2026-07-22", visitors: 187, engaged: 109, converted: 13 },
    { date: "2026-07-23", visitors: 169, engaged: 98, converted: 11 },
    { date: "2026-07-24", visitors: 218, engaged: 123, converted: 15 },
    { date: "2026-07-25", visitors: 255, engaged: 154, converted: 21 },
  ],
  channels: [
    {
      key: "direct",
      label: "Direct",
      detail: "direct / none",
      visitors: 512,
      engagedRate: 0.641,
      conversions: 31,
    },
    {
      key: "organic-search",
      label: "Organic Search",
      detail: "Google, Bing, Yahoo",
      visitors: 428,
      engagedRate: 0.61,
      conversions: 29,
    },
    {
      key: "social",
      label: "Social",
      detail: "X, Instagram, LinkedIn",
      visitors: 162,
      engagedRate: 0.481,
      conversions: 9,
    },
    {
      key: "ai-referral",
      label: "AI Referral",
      detail: "ChatGPT, Perplexity, Claude",
      visitors: 88,
      engagedRate: 0.545,
      conversions: 8,
    },
    {
      key: "campaigns",
      label: "Campaigns",
      detail: "email, ads, newsletter",
      visitors: 58,
      engagedRate: 0.5,
      conversions: 7,
    },
  ],
  referrers: [
    {
      key: "google.com",
      label: "google.com",
      detail: "Organic Search",
      visitors: 332,
      engagedRate: 0.63,
      conversions: 24,
    },
    {
      key: "x.com",
      label: "x.com",
      detail: "Social",
      visitors: 91,
      engagedRate: 0.47,
      conversions: 4,
    },
    {
      key: "chatgpt.com",
      label: "chatgpt.com",
      detail: "AI Referral",
      visitors: 54,
      engagedRate: 0.57,
      conversions: 6,
    },
    {
      key: "instagram.com",
      label: "instagram.com",
      detail: "Social",
      visitors: 43,
      engagedRate: 0.51,
      conversions: 3,
    },
    {
      key: "perplexity.ai",
      label: "perplexity.ai",
      detail: "AI Referral",
      visitors: 23,
      engagedRate: 0.52,
      conversions: 2,
    },
  ],
  campaigns: [
    {
      key: "newsletter_jun24",
      label: "newsletter_jun24",
      detail: "email",
      visitors: 38,
      engagedRate: 0.55,
      conversions: 5,
    },
    {
      key: "launch_x",
      label: "launch_x",
      detail: "paid_social",
      visitors: 20,
      engagedRate: 0.4,
      conversions: 2,
    },
  ],
  utmSources: [
    {
      key: "newsletter",
      label: "newsletter",
      detail: "email",
      visitors: 38,
      engagedRate: 0.55,
      conversions: 5,
    },
    {
      key: "x",
      label: "x",
      detail: "paid_social",
      visitors: 20,
      engagedRate: 0.4,
      conversions: 2,
    },
  ],
  landingPages: [
    { path: "/", visitors: 402, conversionRate: 0.075 },
    { path: "/pricing", visitors: 186, conversionRate: 0.091 },
    { path: "/features", visitors: 148, conversionRate: 0.068 },
    { path: "/blog/best-crm-2024", visitors: 92, conversionRate: 0.043 },
    { path: "/about", visitors: 67, conversionRate: 0.052 },
  ],
  visitors: [
    {
      id: "demo-coral-otter",
      alias: "Coral Otter",
      countryCode: "US",
      browser: "Chrome",
      os: "macOS",
      device: "Desktop",
      channel: "Organic Search",
      source: "Google",
      lastSeen: "2026-07-25T05:24:00.000Z",
      journey: ["/", "/features", "/pricing", "/checkout"],
      converted: true,
    },
    {
      id: "demo-sage-lynx",
      alias: "Sage Lynx",
      countryCode: "GB",
      browser: "Edge",
      os: "Windows",
      device: "Desktop",
      channel: "Direct",
      source: "Direct / none",
      lastSeen: "2026-07-25T04:58:00.000Z",
      journey: ["/", "/pricing", "/about"],
      converted: false,
    },
    {
      id: "demo-amber-falcon",
      alias: "Amber Falcon",
      countryCode: "CA",
      browser: "Safari",
      os: "iOS",
      device: "Mobile",
      channel: "AI Referral",
      source: "ChatGPT",
      lastSeen: "2026-07-25T04:41:00.000Z",
      journey: ["/features", "/pricing", "/checkout", "/success"],
      converted: true,
    },
    {
      id: "demo-indigo-fox",
      alias: "Indigo Fox",
      countryCode: "AU",
      browser: "Safari",
      os: "macOS",
      device: "Desktop",
      channel: "Social",
      source: "X",
      lastSeen: "2026-07-25T04:17:00.000Z",
      journey: ["/blog/best-crm-2024", "/", "/pricing"],
      converted: false,
    },
    {
      id: "demo-willow-deer",
      alias: "Willow Deer",
      countryCode: "DE",
      browser: "Chrome",
      os: "Android",
      device: "Mobile",
      channel: "Campaigns",
      source: "newsletter",
      lastSeen: "2026-07-25T03:45:00.000Z",
      journey: ["/", "/features", "/pricing"],
      converted: false,
    },
  ],
  crawlers: {
    requests: 225,
    verified: 0,
    detectionLabel: "User-agent detected",
    series: [
      { date: "2026-07-19", category: "ai_answer", requests: 8 },
      { date: "2026-07-20", category: "ai_answer", requests: 24 },
      { date: "2026-07-21", category: "ai_answer", requests: 7 },
      { date: "2026-07-22", category: "ai_answer", requests: 22 },
      { date: "2026-07-23", category: "ai_answer", requests: 10 },
      { date: "2026-07-24", category: "ai_answer", requests: 9 },
      { date: "2026-07-25", category: "ai_answer", requests: 15 },
      { date: "2026-07-19", category: "search_index", requests: 7 },
      { date: "2026-07-20", category: "search_index", requests: 18 },
      { date: "2026-07-21", category: "search_index", requests: 6 },
      { date: "2026-07-22", category: "search_index", requests: 16 },
      { date: "2026-07-23", category: "search_index", requests: 8 },
      { date: "2026-07-24", category: "search_index", requests: 7 },
      { date: "2026-07-25", category: "search_index", requests: 10 },
      { date: "2026-07-19", category: "model_training", requests: 6 },
      { date: "2026-07-20", category: "model_training", requests: 16 },
      { date: "2026-07-21", category: "model_training", requests: 6 },
      { date: "2026-07-22", category: "model_training", requests: 13 },
      { date: "2026-07-23", category: "model_training", requests: 6 },
      { date: "2026-07-24", category: "model_training", requests: 6 },
      { date: "2026-07-25", category: "model_training", requests: 5 },
    ],
    providers: [
      { provider: "ChatGPT", requests: 95, share: 0.422 },
      { provider: "OpenAI", requests: 48, share: 0.213 },
      { provider: "Google", requests: 44, share: 0.196 },
      { provider: "Perplexity", requests: 24, share: 0.107 },
      { provider: "Anthropic", requests: 14, share: 0.062 },
    ],
    pages: [
      { path: "/pricing", requests: 38 },
      { path: "/", requests: 29 },
      { path: "/features", requests: 21 },
      { path: "/blog/best-crm-2024", requests: 18 },
      { path: "/docs/api/overview", requests: 12 },
    ],
    categories: [
      { category: "ai_answer", requests: 95 },
      { category: "search_index", requests: 72 },
      { category: "model_training", requests: 58 },
    ],
  },
};

export function emptyAcquisitionSnapshot(
  mode: "empty" | "unavailable" = "empty",
): AcquisitionSnapshot {
  return {
    mode,
    generatedAt: new Date().toISOString(),
    windowDays: 7,
    totals: {
      visitors: 0,
      sessions: 0,
      pageviews: 0,
      engaged: 0,
      converted: 0,
      online: 0,
      averageSessionSeconds: 0,
    },
    series: [],
    channels: [],
    referrers: [],
    campaigns: [],
    utmSources: [],
    landingPages: [],
    visitors: [],
    crawlers: {
      requests: 0,
      verified: 0,
      series: [],
      providers: [],
      pages: [],
      categories: [],
      detectionLabel: "User-agent detected",
    },
  };
}
