import type { DashboardSnapshot } from "@/lib/contracts";

export const demoSnapshot: DashboardSnapshot = {
  mode: "demo",
  generatedAt: "2026-07-23T10:00:00.000Z",
  workspaceName: "Demo workspace",
  app: {
    id: "car-dealer-tracker",
    name: "Car Dealer Tracker",
    platform: "iOS",
    storefront: "United States",
    period: "Last 30 days",
  },
  confidence: {
    score: 92,
    level: "high",
    note: "4 sources synced · last refresh 18m ago",
  },
  stages: [
    {
      id: "discover",
      label: "Discover",
      value: 2410000,
      formattedValue: "2.41M",
      conversionRate: null,
      health: "healthy",
      source: "app-store-connect",
      evidenceIds: ["ev-discovery"],
      flowWidth: 154,
      benchmark: 0.55,
    },
    {
      id: "store",
      label: "Store",
      value: 1340000,
      formattedValue: "1.34M",
      conversionRate: 0.556,
      health: "healthy",
      source: "app-store-connect",
      evidenceIds: ["ev-discovery"],
      flowWidth: 132,
      benchmark: 0.52,
    },
    {
      id: "install",
      label: "Install",
      value: 312000,
      formattedValue: "312K",
      conversionRate: 0.233,
      health: "watch",
      source: "app-store-connect",
      evidenceIds: ["ev-install"],
      flowWidth: 94,
      benchmark: 0.26,
    },
    {
      id: "activate",
      label: "Activate",
      value: 78000,
      formattedValue: "78K",
      conversionRate: 0.25,
      health: "critical",
      source: "posthog",
      evidenceIds: ["ev-activation"],
      flowWidth: 34,
      benchmark: 0.41,
    },
    {
      id: "paywall",
      label: "Paywall",
      value: 62000,
      formattedValue: "62K",
      conversionRate: 0.795,
      health: "healthy",
      source: "superwall",
      evidenceIds: ["ev-paywall"],
      flowWidth: 76,
      benchmark: 0.73,
    },
    {
      id: "trial",
      label: "Trial",
      value: 36000,
      formattedValue: "36K",
      conversionRate: 0.581,
      health: "healthy",
      source: "revenuecat",
      evidenceIds: ["ev-trial"],
      flowWidth: 64,
      benchmark: 0.49,
    },
    {
      id: "paid",
      label: "Paid",
      value: 18000,
      formattedValue: "18K",
      conversionRate: 0.5,
      health: "healthy",
      source: "revenuecat",
      evidenceIds: ["ev-paid"],
      flowWidth: 53,
      benchmark: 0.43,
    },
    {
      id: "renew",
      label: "Renew",
      value: 9000,
      formattedValue: "9K",
      conversionRate: 0.5,
      health: "watch",
      source: "revenuecat",
      evidenceIds: ["ev-renew"],
      flowWidth: 42,
      benchmark: 0.56,
    },
  ],
  events: [
    {
      id: "event-screenshots",
      occurredAt: "2026-07-03T12:00:00.000Z",
      label: "New screenshots",
      detail: "Screenshot set B published",
      type: "screenshots",
      color: "teal",
    },
    {
      id: "event-release",
      occurredAt: "2026-07-09T09:30:00.000Z",
      label: "Version 2.4",
      detail: "Onboarding simplified",
      type: "release",
      color: "blue",
    },
    {
      id: "event-price",
      occurredAt: "2026-07-15T18:00:00.000Z",
      label: "Price $4.99 → $5.99",
      detail: "Monthly plan price changed",
      type: "price",
      color: "coral",
    },
    {
      id: "event-paywall",
      occurredAt: "2026-07-21T15:00:00.000Z",
      label: "Paywall B launched",
      detail: "Outcome-first paywall experiment",
      type: "paywall",
      color: "violet",
    },
  ],
  evidence: [
    {
      id: "ev-activation",
      title: "Activation fell after onboarding release",
      finding:
        "First vehicle created within 24 hours dropped while store and install traffic stayed within their normal ranges.",
      source: "posthog",
      metricKeys: ["activation_24h", "first_vehicle_created"],
      window: {
        from: "2026-07-09T00:00:00.000Z",
        to: "2026-07-23T00:00:00.000Z",
      },
      confidence: "high",
      before: { label: "Before v2.4", value: "41.2%" },
      after: { label: "After v2.4", value: "25.0%" },
    },
    {
      id: "ev-install",
      title: "Store conversion trails benchmark",
      finding:
        "Product page conversion is slightly below comparable productivity apps, but the loss is smaller than activation.",
      source: "app-store-connect",
      metricKeys: ["product_page_views", "downloads"],
      window: {
        from: "2026-06-24T00:00:00.000Z",
        to: "2026-07-23T00:00:00.000Z",
      },
      confidence: "high",
      before: { label: "Category median", value: "26.0%" },
      after: { label: "Your app", value: "23.3%" },
    },
    {
      id: "ev-renew",
      title: "Renewal needs more volume",
      finding:
        "The current renewal cohort is directionally weak but not yet large enough for a confident intervention.",
      source: "revenuecat",
      metricKeys: ["renewal_rate", "active_subscriptions"],
      window: {
        from: "2026-06-24T00:00:00.000Z",
        to: "2026-07-23T00:00:00.000Z",
      },
      confidence: "medium",
      before: { label: "Expected", value: "56.0%" },
      after: { label: "Observed", value: "50.0%" },
    },
    {
      id: "ev-discovery",
      title: "Discovery is stable",
      finding:
        "Impressions and tracked keyword visibility are inside the expected 30-day range.",
      source: "appclimb-rank",
      metricKeys: ["impressions", "keyword_visibility"],
      window: {
        from: "2026-06-24T00:00:00.000Z",
        to: "2026-07-23T00:00:00.000Z",
      },
      confidence: "high",
      before: { label: "Previous", value: "2.28M" },
      after: { label: "Current", value: "2.41M" },
    },
    {
      id: "ev-paywall",
      title: "Paywall reach is healthy",
      finding:
        "Most activated users see the paywall and the new variant has not degraded reach.",
      source: "superwall",
      metricKeys: ["paywall_view_rate"],
      window: {
        from: "2026-07-09T00:00:00.000Z",
        to: "2026-07-23T00:00:00.000Z",
      },
      confidence: "high",
      before: { label: "Previous", value: "76.8%" },
      after: { label: "Current", value: "79.5%" },
    },
    {
      id: "ev-trial",
      title: "Trial starts remain healthy",
      finding:
        "Trial conversion is above the trailing benchmark for the selected storefront.",
      source: "revenuecat",
      metricKeys: ["trial_start_rate"],
      window: {
        from: "2026-06-24T00:00:00.000Z",
        to: "2026-07-23T00:00:00.000Z",
      },
      confidence: "high",
      before: { label: "Benchmark", value: "49.0%" },
      after: { label: "Observed", value: "58.1%" },
    },
    {
      id: "ev-paid",
      title: "Trial-to-paid is above baseline",
      finding:
        "Paid conversion is not the earliest material constraint in the selected period.",
      source: "revenuecat",
      metricKeys: ["trial_to_paid"],
      window: {
        from: "2026-06-24T00:00:00.000Z",
        to: "2026-07-23T00:00:00.000Z",
      },
      confidence: "high",
      before: { label: "Benchmark", value: "43.0%" },
      after: { label: "Observed", value: "50.0%" },
    },
  ],
  insights: [
    {
      id: "insight-activation",
      title: "Fix first-session activation",
      summary: "The first confirmed bottleneck is between install and activation.",
      kind: "Derived",
      stageId: "activate",
      evidenceIds: ["ev-activation"],
      confidence: "high",
      impact: "high",
      effort: "medium",
      rank: 1,
    },
    {
      id: "insight-store",
      title: "Test screenshot promise",
      summary: "Store conversion is 2.7 points below the storefront benchmark.",
      kind: "Observed",
      stageId: "install",
      evidenceIds: ["ev-install"],
      confidence: "high",
      impact: "medium",
      effort: "low",
      rank: 2,
    },
    {
      id: "insight-renewal",
      title: "Watch the renewal cohort",
      summary: "Renewal is soft, but another cohort is required before acting.",
      kind: "Hypothesis",
      stageId: "renew",
      evidenceIds: ["ev-renew"],
      confidence: "medium",
      impact: "medium",
      effort: "medium",
      rank: 3,
    },
  ],
  actionProposals: [
    {
      id: "action-activation",
      insightId: "insight-activation",
      title: "Run a shorter onboarding experiment",
      rationale:
        "Remove one setup step and measure first vehicle creation within 24 hours.",
      experimentTemplate: "activation-onboarding",
      status: "proposed",
      externalMutationAllowed: false,
    },
    {
      id: "action-store",
      insightId: "insight-store",
      title: "Test outcome-first screenshot #1",
      rationale:
        "Show the completed inventory workflow before product UI details.",
      experimentTemplate: "store-screenshot",
      status: "proposed",
      externalMutationAllowed: false,
    },
    {
      id: "action-renewal",
      insightId: "insight-renewal",
      title: "Wait for the next renewal cohort",
      rationale:
        "Avoid optimizing against a low-volume cohort with medium confidence.",
      experimentTemplate: "renewal-observation",
      status: "proposed",
      externalMutationAllowed: false,
    },
  ],
  experiments: [
    {
      id: "experiment-onboarding",
      title: "Fast path onboarding",
      stageId: "activate",
      hypothesis:
        "Letting dealers create the first vehicle before configuring the workspace will improve activation.",
      primaryMetric: "First vehicle created within 24h",
      guardrailMetric: "D7 retained dealer",
      status: "ready",
      source: "posthog",
    },
    {
      id: "experiment-paywall",
      title: "Outcome-first paywall",
      stageId: "trial",
      hypothesis:
        "Leading with time saved will increase trial starts without reducing paid conversion.",
      primaryMetric: "Trial start rate",
      guardrailMetric: "Trial to paid",
      status: "running",
      source: "superwall",
      startedAt: "2026-07-21T15:00:00.000Z",
    },
  ],
  sources: [
    {
      provider: "app-store-connect",
      label: "App Store Connect",
      status: "connected",
      lastSyncAt: "2026-07-23T09:42:00.000Z",
      freshnessHours: 0.3,
      capabilities: ["Store engagement", "Sales", "Usage", "Performance"],
      readOnly: true,
    },
    {
      provider: "revenuecat",
      label: "RevenueCat",
      status: "connected",
      lastSyncAt: "2026-07-23T09:51:00.000Z",
      freshnessHours: 0.15,
      capabilities: ["Trials", "Revenue", "Renewals", "Churn"],
      readOnly: true,
    },
    {
      provider: "posthog",
      label: "PostHog",
      status: "connected",
      lastSyncAt: "2026-07-23T09:48:00.000Z",
      freshnessHours: 0.2,
      capabilities: ["Activation", "Funnels", "Retention", "Feature usage"],
      readOnly: true,
    },
    {
      provider: "superwall",
      label: "Superwall",
      status: "connected",
      lastSyncAt: "2026-07-23T09:45:00.000Z",
      freshnessHours: 0.25,
      capabilities: ["Paywall views", "Experiments", "Conversion"],
      readOnly: true,
    },
    {
      provider: "appclimb-rank",
      label: "Keyword monitor",
      status: "not-connected",
      capabilities: ["Private beta", "100 keywords", "3 storefronts"],
      readOnly: true,
    },
  ],
  retention: [
    { cohort: "Jun 16", values: [100, 64, 51, 43, 38, 34] },
    { cohort: "Jun 23", values: [100, 68, 56, 47, 41, 36] },
    { cohort: "Jun 30", values: [100, 66, 52, 44, 37, 32] },
    { cohort: "Jul 7", values: [100, 51, 38, 31, 27, 22] },
    { cohort: "Jul 14", values: [100, 49, 36, 29, 24, 0] },
    { cohort: "Jul 21", values: [100, 61, 0, 0, 0, 0] },
  ],
  customerClusters: [
    {
      id: "cluster-easy",
      label: "Easy to use",
      mentions: 128,
      sentiment: "positive",
      x: 30,
      y: 40,
      radius: 54,
    },
    {
      id: "cluster-sync",
      label: "Sync issues",
      mentions: 74,
      sentiment: "negative",
      x: 68,
      y: 34,
      radius: 42,
    },
    {
      id: "cluster-reports",
      label: "Better reports",
      mentions: 52,
      sentiment: "mixed",
      x: 55,
      y: 72,
      radius: 36,
    },
    {
      id: "cluster-speed",
      label: "Fast workflow",
      mentions: 41,
      sentiment: "positive",
      x: 17,
      y: 77,
      radius: 31,
    },
  ],
};
